# Generated by Django 4.1.7 on 2023-09-14 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curingApp.pole')),
            ],
        ),
    ]
